Dropdown component
mirceabozianu/e-commerce pull request #4
Opened 2021-09-15 08:38 UTC by mirceabozianu

2021-09-15 10:02 UTC, iftodimihail commented on src/components/common/Dropdown/index.js
> +      onClick={trigger === "click" ? handleClick : null}
as face verificarea asta in functie direct. 
```
if(trigger !== "click") {
  return;
}
setIsOpen((prevState) => !prevState);
```

2021-09-15 10:02 UTC, iftodimihail requested changes

2021-09-15 10:02 UTC, iftodimihail commented on src/components/common/Dropdown/index.js
> +      onClick={trigger === "click" ? handleClick : null}
as face verificarea asta in functie direct. 
```
if(trigger !== "click") {
  return;
}
setIsOpen((prevState) => !prevState);
```

2021-09-15 10:16 UTC, oana-anghelache commented on src/components/common/Dropdown/index.js
> +const showDropdownContent = css`
you used a verb to describe these styles but this is not an action. You should rename this to something like: visibleDropdownStyles

2021-09-15 10:23 UTC, oana-anghelache commented on src/components/common/Dropdown/index.js
> +          <StyledDropdownItem href={`/${item}`} key={index}>
use a different prop for the href. Your dropdown item name might be "User Name" and the href value '/my-profile'

2021-09-15 10:26 UTC, oana-anghelache commented on src/components/common/Dropdown/index.js
> +          <StyledDropdownItem href={`/${item}`} key={index}>
you used StyledDropdownContent as a `div` element and added href on a div. I would suggest using the React `<Link to={path} />` for this. And style this link: 
```
StyledLink = styled(Link)``
```

2021-09-15 10:30 UTC, oana-anghelache commented on src/components/common/layouts/NavBar/index.js
> +  }, []);
I wouldn't fetch items in a common component. Keep these files as stateless as possible and just style the navigation menu. The items should be send through props. Think of a way to structure your data. The menu has some items and an item can have other subitems / children (this is where you should use the dropdown).

2021-09-15 10:32 UTC, oana-anghelache commented on src/components/common/layouts/NavBar/index.js
> +  }, []);
the navigation menu will have in the future other items like `account` instead of sign in. This component should be more generic to cover all these cases

2021-09-15 10:42 UTC, iftodimihail commented on src/components/common/Dropdown/index.js
> +const showDropdownContent = css`
aici eu sunt de vina, eu cred ca i-am dat ideea aia de nume :D

2021-09-15 10:43 UTC, oana-anghelache commented on src/components/common/Dropdown/index.js
> +const showDropdownContent = css`
nicio problema

2021-09-20 07:37 UTC, oana-anghelache commented on src/App.js
> +
move this into a use memo. This result depends on the categories data

2021-09-20 07:43 UTC, oana-anghelache commented on src/components/common/Dropdown/index.js
> +          <StyledLink to={`/${item}`} key={index}>
to={item.path}

2021-09-20 07:43 UTC, oana-anghelache commented on src/components/common/Dropdown/index.js
> +            {item}
item.name

2021-09-20 07:44 UTC, oana-anghelache commented on src/pages/Dashboard/index.js
>        <Categories data={data} />
rename `data` into `categories`, to be more specific

2021-09-20 14:03 UTC, oana-anghelache approved these changes

2021-09-20 14:43 UTC, merged