Register
mirceabozianu/e-commerce pull request #5
Opened 2021-09-20 13:46 UTC by mirceabozianu

2021-09-20 15:19 UTC, oana-anghelache requested changes

2021-09-20 15:19 UTC, oana-anghelache commented on src/pages/Auth/components/styledForm.js
> +    background-color: rgba(232, 232, 232, 1);
You already have a component for the input inside: common/styled/Input. Try to customize it and only use this `<Input />`. You can style the input here and you can also turn it into a component that includes the error message bellow as well.

2021-09-20 15:19 UTC, oana-anghelache commented on src/services/localStorage.js
> +  oldUsers.push({ name, email, password });
Never mutate data outside this function. `push` will mutate the 'oldUsers' array. `oldUsers` is also exported and can be used in many different parts of your application. This might trigger unexpected behavior

2021-09-20 15:19 UTC, oana-anghelache commented on src/services/localStorage.js
> +}
no need for these lines. Here, all you need to export are two functions that will `set` users and `get` users.

getUsers() - returns the list of users
setUsers(users) - will set the new list of users into local storage

2021-09-20 15:19 UTC, oana-anghelache commented on src/services/localStorage.js
> +  oldUsers.push({ name, email, password });
check the previous comment. Data transformation should not happen here.

2021-09-20 15:28 UTC, oana-anghelache commented on src/components/common/Dropdown/index.js
> +<<<<<<< HEAD
You haven't resolved your conflicts. This should be done before committing and pushing the changes: 
1. merge master into your branch
2. Make sure you solve all conflicts
3. Check again all files and changes
4. Commit and push

2021-09-20 15:30 UTC, oana-anghelache commented on src/components/common/Dropdown/index.js
> +<<<<<<< HEAD
In this case, you should keep the dropdown changes from master.

2021-09-20 18:08 UTC, iftodimihail requested changes

2021-09-20 18:08 UTC, iftodimihail commented on src/pages/Auth/Register/index.js
> +            )}
Like Oana said, You alreayd have an `Input` component. Make it more specific so everywhere you will use an input it will be the same. Move it into `components/common` since it will be even more explitcit and will also contain the `ErrorText` component and a label.

2021-09-24 08:27 UTC, iftodimihail requested changes

2021-09-24 08:27 UTC, iftodimihail commented on src/pages/Auth/Register/index.js
> +            validators={nameValidators}
instead of validators send the errors

2021-09-24 08:27 UTC, iftodimihail commented on src/utils/hooks.js
> +  const [isTouched, setIsTouched] = useState(false);
const [errors, setErrors] = useState([]);

2021-09-24 08:27 UTC, iftodimihail commented on src/utils/hooks.js
> +export const useInput = () => {
add validators as argument

2021-09-24 08:27 UTC, iftodimihail commented on src/utils/hooks.js
> +  };
set input errors

2021-09-24 08:27 UTC, iftodimihail commented on src/components/common/Input/index.js
> +    ));
map through the errors received

2021-09-24 08:27 UTC, iftodimihail commented on src/utils/hooks.js
> +  };
validators.map(validator => validator(enteredValue))

2021-09-24 08:27 UTC, iftodimihail commented on src/pages/Auth/Register/index.js
> +    .flat()
const isFormValid = [...nameField.erorrs, ....].length > 0

2021-09-27 07:19 UTC, iftodimihail requested changes

2021-09-27 07:19 UTC, iftodimihail commented on src/pages/Auth/Register/index.js
> +  const confirmPassInputField = useInput();
send the validator on `useInput(validator)` so you can also return the errors upon the calling of the hook

2021-09-27 07:19 UTC, iftodimihail commented on src/pages/Auth/Register/index.js
> +    isSamePassword(passwordInputField.value, confirmPassInputField.value),
errors will be sent by the useInput hook

2021-09-27 07:19 UTC, iftodimihail commented on src/components/common/Input/index.js
> +      {otherProps.isTouched && displayErrorMessages}
like I said in the previous call, you don't need this `isTouched` prop

2021-09-27 07:19 UTC, iftodimihail commented on src/components/common/Input/index.js
> +      {otherProps.isTouched && displayErrorMessages}
you will deal with the error handling in the `useInput` hook on the `onBlur` function

2021-09-27 07:36 UTC, iftodimihail commented on src/pages/Auth/Register/index.js
> +    isSamePassword(passwordInputField.value, confirmPassInputField.value),
only the errors that requiredvalues from different inputs will be displayed here

2021-09-27 07:37 UTC, iftodimihail commented on src/pages/Auth/Register/index.js
> +    isSamePassword(passwordInputField.value, confirmPassInputField.value),
<Input name="confirmPassword errors={[...confirmPasswordField.errors, arePasswordsIdentical]} />

2021-09-27 11:49 UTC, iftodimihail approved these changes

2021-09-27 12:49 UTC, merged

2021-09-27 12:52 UTC, oana-anghelache commented on src/pages/Auth/Register/index.js
> +  const getErrorMessages = (...errors) => {
usually, this is written as (...args) => {} and all the parameters will be assigned to an array.
No need to do that.

Here, write:
```
const getErrorMessages = (errors) => {
  return errors.filter((error) => Boolean(error) !== false);
}
```

when checking `isFormNotValid` , write:
```
getErrorMessages([...nameErrors, ...emailErrors, ...passwordErrors, ...confirmPassErrors]);
```
or
```
getErrorMessages([nameErrors, emailErrors, passwordErrors, confirmPassErrors].flat())
```

2021-09-27 13:08 UTC, oana-anghelache commented on src/components/common/Input/index.js
> +      {otherProps.isTouched && displayErrorMessages}
displayErrorMessages - I'm assuming this is a function but instead it's the list of errors.
better have:
```
const renderError = (error, index) => (<ErrorText key={index}>{errorMessage}</ErrorText>)
...
{otherProps.isTouched && errors.map(renderError)}

...

```

or

```
function displayErrorMessages() {
  if(!rest.isTouched) {
    return null;
  }
  return errors.map((errorMessage) => (
    <ErrorText key={errorMessage}>{errorMessage}</ErrorText>
  ));
}

....

{displayErrorMessages()}
```